### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by berubou** [EBoost-Chair/ruby-roguelike#1]
1. description improve
    -  let me know what i can do & where am i
1. input check
    - repeat Enter. and the game works still
1. encapsulation
    - like in the func move and moveEnemy, u don't need so many if state

hope this helps.  :)

**Comment by EBoost-Chair** [comment]
@berubou First,thanks for giving me so much advice. :)
1.I will add some input check to the game loop,and there's a "h" or "help" command.You can see the help page.
2.I've never thought about that before.Thanks again. 
3.move and moveEnemy includes game's system(e.g. lava( "X" ) will hurt player.),I'm now thinking about the way to improve it. 
P.S. next testing version will come out this weekend,and some of the problems will be solved.

**Comment by EBoost-Chair** [comment]
@berubou  These suggestions have been used in the newest version(Test version 2),Thanks a lot. :)

**Comment by berubou** [comment]
newest version -> latest version.
i'll scan it sometimes later
